### ISSUE TITLE
您好，想学习一下您的系统，但是打开http://127.0.0.1:8000/后报错如下，这是什么问题呢？（运行程序的电脑打开的，是这个问题吗？）

### ISSUE THREAD

**Issue by Wayfarer-coder** [secrul/factory-manage#2]
C:\Users\Mikeal Liu>python D:\desktop\factory-manage-master\manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
September 16, 2020 - 23:18:47
Django version 3.1.1, using settings 'factory.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\desktop\factory-manage-master\factory\views.py", line 10, in home
    return render(request, 'home.html', context)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "C:\Users\Mikeal Liu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\template\defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[16/Sep/2020 23:20:17] "GET / HTTP/1.1" 500 146921

另外我们企业想要加装新的功能等，您有时间给我们做更新吗？不知道费用如何

**Comment by secrul** [comment]
您好！这个可能是是环境的问题，也可能是您修改了数据库定义代码。尝试运行一个“python manage.py migrate” 来更新一下数据库。后续我可能没有时间，导师这边事情比较多，不好意思，随缘更吧，大概率不会更新了。

**Comment by Wayfarer-coder** [comment]
> 您好！这个可能是是环境的问题，也可能是您修改了数据库定义代码。尝试运行一个“python manage.py migrate” 来更新一下数据库。后续我可能没有时间，导师这边事情比较多，不好意思，随缘更吧，大概率不会更新了。

好的,谢谢,我没有修改数据库代码,我将按照您说的尝试

**Comment by secrul** [comment]
检查一下Python和Django的版本，现在默认Django是4.x，需要回退为2.2. 将staticfiles改为staticf
